### ISSUE TITLE
`populate_db` can't access `/var` directory

### ISSUE THREAD

**Issue by almatrass** [Egiob/csgo_forecasting#5]
Hello,

I'm currently trying to test out this software, and it seems like I'm running into exactly the same issue mentioned by another user here: https://github.com/Egiob/csgo_forecasting/issues/2#issuecomment-757039329.

I'm getting the same `FileNotFoundError: [Errno 2] No such file or directory: './var/teams_map.csv'` error when trying to run `populate_db` - in his issue he says he simply deleted and pulled the repo again and the problem was solved, however this is not working for me.

Do you have any suggestions for fixing this error, or what's going wrong?

Thanks,
Ross

**Comment by krazzarkov** [comment]
Hello,

This issue occurs because of Symlinks not working. 

Make sure to use this command: `git config --global core.symlinks true`. Alternatively, when installing Git via the install wizard, it's important to click on the checkbox referring to enabling symlinks. Also, make sure you are using Git to clone the project. 

The way to verify if the Symlinks worked is to go into the csgo_forcasting folder > notebooks and then look to see if there is a "paris" and "var" folder inside the actual notebooks folder itself. It should look like the screenshot below. 

![image](https://user-images.githubusercontent.com/8461672/108009929-95091c80-6fb8-11eb-84d4-26c88e127085.png)

Hope this helps :)

**Comment by almatrass** [comment]
Hi,

Thanks a lot for your fast reply.

I had already run this command and tried it again several times there but seems like it's still not recognising the symlinks, cloning using both git CLI and Github Desktop, I'll try reinstalling tomorrow and see if that fixes it. (I tried it on my Macbook and it worked without issue).

For now I created the symlinks to the folders manually to get the project up and running and it works perfectly.

For anyone with the same issue and wants to get up and running quick you can run these commands on Windows 10 (desktop folder):

`mklink /J C:\Users\*YOUR_USERNAME*\Desktop\csgo_forecasting\notebooks\paris C:\Users\*YOUR_USERNAME*\Desktop\csgo_forecasting\paris`

`mklink /J C:\Users\*YOUR_USERNAME*\Desktop\csgo_forecasting\notebooks\var C:\Users\*YOUR_USERNAME*\Desktop\csgo_forecasting\var`

Thanks again for your help :)

**Comment by krazzarkov** [comment]
Glad you were able to resolve it

I deployed this project on a server to test it and remembered that I was having issues getting the Symlinks to work even though I had enabled them and even reinstalled Git to try and get it to work. Maybe it's a Windows issue.
